Repository mallangC/Jogakjogak, pull requests merged in 2025-07, with the labels that each got.

#161 JobDescription service에 QueryDSL 적용
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryCustom.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryImpl.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#163 ToDoList Service에 QueryDSL 적용
  src/main/java/com/zb/jogakjogak/global/config/QuerydslConfig.java
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepositoryCustom.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepositoryImpl.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/controller/ToDoListControllerTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#158 알림정책 수정, 이메일암호화
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryCustom.java
  src/main/java/com/zb/jogakjogak/notification/batch/NotificationBatchConfig.java
  src/main/java/com/zb/jogakjogak/notification/config/MetaDBConfig.java
  src/main/java/com/zb/jogakjogak/notification/dto/NotificationDto.java
  src/main/java/com/zb/jogakjogak/notification/repository/NotificationRepository.java
  src/main/java/com/zb/jogakjogak/notification/service/NotificationService.java
  src/main/java/com/zb/jogakjogak/security/config/EmailEncryptor.java
  src/main/java/com/zb/jogakjogak/security/config/EncryptionKeyHolder.java
  src/main/java/com/zb/jogakjogak/security/config/PhoneNumberEncryptor.java
  src/main/java/com/zb/jogakjogak/security/config/SecurityConfig.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/resources/application.yml
  src/main/resources/db/migration/main/V1__create_initial_schema_main.sql
  src/main/resources/db/migration/meta/V1__create_inital_schema_meta.sql
Labels: enhancement

#200 로그아웃, 토큰 재발급 리팩토링
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/controller/WithdrawalController.java
  src/main/java/com/zb/jogakjogak/security/entity/RefreshToken.java
  src/main/java/com/zb/jogakjogak/security/jwt/CustomLogoutFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTUtil.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/repository/RefreshTokenRepository.java
  src/main/java/com/zb/jogakjogak/security/service/ReissueService.java
  src/main/java/com/zb/jogakjogak/security/service/WithdrawalService.java
  src/main/resources/db/migration/main/V2__add_user_id_to_refresh_token.sql
  src/test/java/com/zb/jogakjogak/security/service/ReissueServiceTest.java
Labels: enhancement

#203 ga 설정
  build.gradle
  src/main/java/com/zb/jogakjogak/ga/interceptor/GaApiCallInterceptor.java
  src/main/java/com/zb/jogakjogak/ga/service/GaMeasurementProtocolService.java
  src/main/java/com/zb/jogakjogak/global/config/WebConfig.java
  src/main/java/com/zb/jogakjogak/global/exception/ErrorResponse.java
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/global/util/HashingUtil.java
  src/main/java/com/zb/jogakjogak/notification/service/NotificationService.java
  src/main/java/com/zb/jogakjogak/security/config/SecurityConfig.java
  src/main/java/com/zb/jogakjogak/security/dto/CustomOAuth2User.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/resources/application.yml
  src/test/java/com/zb/jogakjogak/security/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/zb/jogakjogak/security/controller/ReissueTestControllerTest.java
  src/test/java/com/zb/jogakjogak/security/controller/WithdrawalTestControllerTest.java
Labels: documentation, enhancement

#211 회원탈퇴기능 리팩토링
  gradlew
  src/main/java/com/zb/jogakjogak/global/exception/MemberErrorCode.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/controller/WithdrawalController.java
  src/main/java/com/zb/jogakjogak/security/entity/OAuth2Info.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/repository/MemberRepository.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/java/com/zb/jogakjogak/security/service/GoogleWithdrawalService.java
  src/main/java/com/zb/jogakjogak/security/service/KakaoService.java
  src/main/java/com/zb/jogakjogak/security/service/KakaoWithdrawalService.java
  src/main/java/com/zb/jogakjogak/security/service/ReissueService.java
  src/main/java/com/zb/jogakjogak/security/service/WithdrawalService.java
  src/main/resources/db/migration/main/V3__add_access_token_to_oauth2_info.sql
  src/test/java/com/zb/jogakjogak/security/service/WithdrawalServiceTest.java
Labels: enhancement

#216 카카오 로그인 테스트계정->일반계정 로그인 가능
  build.gradle
  src/main/java/com/zb/jogakjogak/ga/service/GaMeasurementProtocolService.java
  src/main/java/com/zb/jogakjogak/global/config/WebConfig.java
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/CreateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/UpdateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryCustom.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryImpl.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/notification/config/NotificationBatchConfig.java
  src/main/java/com/zb/jogakjogak/notification/service/NotificationService.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/resources/application.yml
  src/main/resources/db/migration/main/V4_modify_phone_number_null_able.sql
  src/test/java/com/zb/jogakjogak/security/service/CustomOauth2UserServiceTest.java
Labels: enhancement

#219 회원탈퇴기능 수정
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryCustom.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepositoryImpl.java
  src/main/java/com/zb/jogakjogak/notification/config/NotificationBatchConfig.java
  src/main/java/com/zb/jogakjogak/security/controller/WithdrawalController.java
  src/main/resources/db/migration/main/V4__modify_phone_number_null_able.sql
  src/test/java/com/zb/jogakjogak/security/controller/WithdrawalTestControllerTest.java
Labels: enhancement

#226 유효성 검증 로직 추가
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/global/exception/JDErrorCode.java
  src/main/java/com/zb/jogakjogak/global/validation/EnglishWordDictionary.java
  src/main/java/com/zb/jogakjogak/global/validation/MeaningfulText.java
  src/main/java/com/zb/jogakjogak/global/validation/MeaningfulTextValidator.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/resume/domain/requestDto/ResumeRequestDto.java
  src/test/java/com/zb/jogakjogak/jobDescription/controller/JDControllerTest.java
  src/test/java/com/zb/jogakjogak/resume/controller/ResumeControllerTest.java
  src/test/java/com/zb/jogakjogak/resume/domain/ResumeRequestDtoTest.java
Labels: enhancement

#227 이메일 알림 발송시 notification 저장안되는 버그 수정
  src/main/java/com/zb/jogakjogak/notification/config/NotificationBatchConfig.java
  src/main/java/com/zb/jogakjogak/notification/service/NotificationService.java
Labels: bug
