Repository mallangC/Jogakjogak, pull requests merged in 2025-06, with the labels that each got.

#12 Member, OAuth, Jwt 관련 클래스 추가
  .github/workflows/CI&CD.yml
  build.gradle
  src/main/java/com/zb/jogakjogak/global/exception/CustomException.java
  src/main/java/com/zb/jogakjogak/global/exception/ErrorCode.java
  src/main/java/com/zb/jogakjogak/global/exception/ErrorResponse.java
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/security/Role.java
  src/main/java/com/zb/jogakjogak/security/Token.java
  src/main/java/com/zb/jogakjogak/security/config/CorsMvcConfig.java
  src/main/java/com/zb/jogakjogak/security/config/SecurityConfig.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/dto/CustomOAuth2User.java
  src/main/java/com/zb/jogakjogak/security/dto/KakaoResponseDto.java
  src/main/java/com/zb/jogakjogak/security/dto/ReissueResultDto.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/java/com/zb/jogakjogak/security/entity/RefreshToken.java
  src/main/java/com/zb/jogakjogak/security/jwt/CustomLogoutFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTUtil.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/repository/MemberRepository.java
  src/main/java/com/zb/jogakjogak/security/repository/RefreshTokenRepository.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/java/com/zb/jogakjogak/security/service/ReissueService.java
  src/main/resources/application.yml
  src/test/java/com/zb/jogakjogak/JogakjogakApplicationTests.java
Labels: enhancement

#19 이력서 조회하기
  build.gradle
  src/main/java/com/zb/jogakjogak/JogakjogakApplication.java
  src/main/java/com/zb/jogakjogak/global/BaseEntity.java
  src/main/java/com/zb/jogakjogak/global/exception/ResumeErrorCode.java
  src/main/java/com/zb/jogakjogak/global/exception/ResumeException.java
  src/main/java/com/zb/jogakjogak/resume/controller/ResumeController.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeRequestDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeResponseDto.java
  src/main/java/com/zb/jogakjogak/resume/entity/Resume.java
  src/main/java/com/zb/jogakjogak/resume/repository/ResumeRepository.java
  src/main/java/com/zb/jogakjogak/resume/service/ResumeService.java
  src/test/java/com/zb/jogakjogak/resume/domain/ResumeRequestDtoTest.java
  src/test/java/com/zb/jogakjogak/resume/service/ResumeServiceTest.java
Labels: documentation, enhancement

#21 oauth2 관련 클래스 리팩토링, 테스트 추가
  build.gradle
  src/main/java/com/zb/jogakjogak/global/exception/CustomException.java
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/global/exception/MemberErrorCode.java
  src/main/java/com/zb/jogakjogak/global/exception/SecurityException.java
  src/main/java/com/zb/jogakjogak/security/config/SecurityConfig.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/dto/CustomOAuth2User.java
  src/main/java/com/zb/jogakjogak/security/dto/KakaoResponseDto.java
  src/main/java/com/zb/jogakjogak/security/dto/OAuth2ResponseDto.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/java/com/zb/jogakjogak/security/entity/OAuth2Info.java
  src/main/java/com/zb/jogakjogak/security/jwt/CustomLogoutFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTUtil.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/repository/MemberRepository.java
  src/main/java/com/zb/jogakjogak/security/repository/RefreshTokenRepository.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/java/com/zb/jogakjogak/security/service/ReissueService.java
  src/main/resources/application.yml
  src/test/java/com/zb/jogakjogak/security/controller/ReissueControllerTest.java
  src/test/java/com/zb/jogakjogak/security/integration/ReissueControllerIntegrationTest.java
  src/test/java/com/zb/jogakjogak/security/service/ReissueServiceTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#22 JD 분석시 ToDoList 저장
  build.gradle
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/repsitory/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repsitory/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/OpenAIResponseService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/main/java/com/zb/jogakjogak/jobDescription/type/ToDoListType.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeRequestDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeResponseDto.java
  src/main/java/com/zb/jogakjogak/security/Role.java
  src/main/java/com/zb/jogakjogak/security/Token.java
  src/main/java/com/zb/jogakjogak/security/config/CorsMvcConfig.java
  src/main/java/com/zb/jogakjogak/security/config/SecurityConfig.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/dto/CustomOAuth2User.java
  src/main/java/com/zb/jogakjogak/security/dto/KakaoResponseDto.java
  src/main/java/com/zb/jogakjogak/security/dto/OAuth2ResponseDto.java
  src/main/java/com/zb/jogakjogak/security/dto/ReissueResultDto.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/java/com/zb/jogakjogak/security/entity/OAuth2Info.java
  src/main/java/com/zb/jogakjogak/security/entity/RefreshToken.java
  src/main/java/com/zb/jogakjogak/security/jwt/CustomLogoutFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTUtil.java
  src/main/java/com/zb/jogakjogak/security/oauth2/CustomSuccessHandler.java
  src/main/java/com/zb/jogakjogak/security/repository/MemberRepository.java
  src/main/java/com/zb/jogakjogak/security/repository/RefreshTokenRepository.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/java/com/zb/jogakjogak/security/service/ReissueService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/security/controller/ReissueControllerTest.java
  src/test/java/com/zb/jogakjogak/security/integration/ReissueControllerIntegrationTest.java
  src/test/java/com/zb/jogakjogak/security/service/ReissueServiceTest.java
Labels: documentation, enhancement

#27 ToDoList 수정하기
  build.gradle
  src/main/java/com/zb/jogakjogak/global/exception/JDErrorCode.java
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListErrorCode.java
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListException.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/OpenAIResponseService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/main/java/com/zb/jogakjogak/jobDescription/type/ToDoListType.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#31 CustomOauth2UserServiceTest작성
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/security/entity/OAuth2Info.java
  src/test/java/com/zb/jogakjogak/security/service/CustomOauth2UserServiceTest.java
  src/test/java/com/zb/jogakjogak/security/service/ReissueServiceTest.java
Labels: enhancement

#36 회원탈퇴 기능
  src/main/java/com/zb/jogakjogak/global/exception/AuthException.java
  src/main/java/com/zb/jogakjogak/global/exception/GlobalExceptionHandler.java
  src/main/java/com/zb/jogakjogak/global/exception/MemberErrorCode.java
  src/main/java/com/zb/jogakjogak/security/config/RestTemplateConfig.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/controller/WithdrawalController.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTFilter.java
  src/main/java/com/zb/jogakjogak/security/jwt/JWTUtil.java
  src/main/java/com/zb/jogakjogak/security/repository/MemberRepository.java
  src/main/java/com/zb/jogakjogak/security/repository/RefreshTokenRepository.java
  src/main/java/com/zb/jogakjogak/security/service/CustomOauth2UserService.java
  src/main/java/com/zb/jogakjogak/security/service/KakaoService.java
  src/main/java/com/zb/jogakjogak/security/service/WithdrawalService.java
  src/main/resources/application.yml
  src/test/java/com/zb/jogakjogak/security/controller/ReissueControllerTest.java
  src/test/java/com/zb/jogakjogak/security/controller/WithdrawalControllerTest.java
  src/test/java/com/zb/jogakjogak/security/integration/ReissueControllerIntegrationTest.java
  src/test/java/com/zb/jogakjogak/security/service/WithdrawalServiceTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#34 Open Ai에서 Gemini Ai로 분석 ai 바꾸기
  build.gradle
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/resume/controller/ResumeController.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/main/resources/application.yml
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
Labels: documentation, enhancement

#37 To do list 삭제하기 기능
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListDeleteResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#38 Todo list 단건 조회하기 기능
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#41 분석내용단건조회
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/repsitory/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#45 JD 알림 설정 기능
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDAlarmRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDAlarmResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
Labels: documentation, enhancement

#49 카테고리별 조회 후 todolist 다중 수정 기능
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/BulkToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListGetByCategoryResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/repsitory/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#67 jd 분석내용전체조회 기능
  src/main/java/com/zb/jogakjogak/global/exception/MemberErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/AllGetJDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/PagedJdResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/JDRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/resume/controller/ResumeController.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeRequestDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/ResumeResponseDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/requestDto/ResumeRequestDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/responseDto/ResumeResponseDto.java
  src/main/java/com/zb/jogakjogak/resume/entity/Resume.java
  src/main/java/com/zb/jogakjogak/resume/service/ResumeService.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/resume/domain/ResumeRequestDtoTest.java
  src/test/java/com/zb/jogakjogak/resume/service/ResumeServiceTest.java
Labels: documentation, enhancement

#84 지원 완료 / 즐겨 찾기 기능 추가
  src/main/java/com/zb/jogakjogak/global/exception/JDErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/JDController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ApplyStatusRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/BookmarkRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ApplyStatusResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/BookmarkResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/JD.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/JDServiceTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement

#120 ResumeControllerTest 작성
  .github/workflows/CI.yml
  build.gradle
  src/main/java/com/zb/jogakjogak/resume/controller/ResumeController.java
  src/main/java/com/zb/jogakjogak/security/entity/Member.java
  src/test/java/com/zb/jogakjogak/resume/controller/ResumeControllerTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#126 체크리스트 추가 기능 리팩토링
  build.gradle
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/CreateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/UpdateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
  src/test/resources/application-test.yml
Labels: documentation, enhancement

#132 이력서 저장 시 유효성 검사 추가
  src/main/java/com/zb/jogakjogak/resume/domain/requestDto/ResumeRequestDto.java
  src/test/java/com/zb/jogakjogak/resume/domain/ResumeRequestDtoTest.java
Labels: enhancement

#148 prompt 수정
  src/main/java/com/zb/jogakjogak/global/exception/JDErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
Labels: bug

#154 Infra/document
  src/main/java/com/zb/jogakjogak/global/config/SwaggerConfig.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ApplyStatusRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/BookmarkRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/BulkToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/CreateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDAlarmRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/JDRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/MemoRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/UpdateToDoListRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ApplyStatusResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/BookmarkResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDAlarmResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/JDResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/MemoResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/PagedJdResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListGetByCategoryResponseDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/responseDto/ToDoListResponseDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/requestDto/ResumeRequestDto.java
  src/main/java/com/zb/jogakjogak/resume/domain/responseDto/ResumeResponseDto.java
  src/main/java/com/zb/jogakjogak/security/controller/ReissueController.java
  src/main/java/com/zb/jogakjogak/security/controller/WithdrawalController.java
Labels: documentation

#153 ToDoListController 통합테스트
  src/main/java/com/zb/jogakjogak/global/exception/ToDoListErrorCode.java
  src/main/java/com/zb/jogakjogak/jobDescription/controller/ToDoListController.java
  src/main/java/com/zb/jogakjogak/jobDescription/domain/requestDto/ToDoListUpdateRequestDto.java
  src/main/java/com/zb/jogakjogak/jobDescription/entity/ToDoList.java
  src/main/java/com/zb/jogakjogak/jobDescription/repository/ToDoListRepository.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/JDService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/LLMService.java
  src/main/java/com/zb/jogakjogak/jobDescription/service/ToDoListService.java
  src/main/java/com/zb/jogakjogak/jobDescription/type/ToDoListType.java
  src/test/java/com/zb/jogakjogak/jobDescription/controller/ToDoListControllerTest.java
  src/test/java/com/zb/jogakjogak/jobDescription/service/ToDoListServiceTest.java
Labels: documentation, enhancement
